-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 20:52:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spotitube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotitube` ;

-- -----------------------------------------------------
-- Schema spotitube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotitube` DEFAULT CHARACTER SET utf8 ;
USE `spotitube` ;

-- -----------------------------------------------------
-- Table `spotitube`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotitube`.`account` (
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotitube`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotitube`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_user` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `owner` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlist_account1_idx` (`account_user` ASC),
  CONSTRAINT `fk_playlist_account`
    FOREIGN KEY (`account_user`)
    REFERENCES `spotitube`.`account` (`user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotitube`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotitube`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlist_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `performer` VARCHAR(255) NOT NULL,
  `duration` INT NOT NULL,
  `album` VARCHAR(255) NOT NULL,
  `playcount` INT NOT NULL,
  `publication_date` DATE NULL,
  `description` VARCHAR(255) NULL,
  `offline_available` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_track_playlist1_idx` (`playlist_id` ASC),
  CONSTRAINT `fk_track_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `spotitube`.`playlist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotitube`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotitube`.`token` (
  `token` VARCHAR(255) NOT NULL,
  `account_user` VARCHAR(255) NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  PRIMARY KEY (`token`),
  INDEX `fk_token_account_idx` (`account_user` ASC),
  CONSTRAINT `fk_token_account`
    FOREIGN KEY (`account_user`)
    REFERENCES `spotitube`.`account` (`user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
